# Generated by Django 3.1.7 on 2021-03-14 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Details',
            fields=[
                ('name', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('field', models.CharField(max_length=20)),
            ],
        ),
    ]
