# Generated by Django 3.1.7 on 2021-03-14 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phonebook', '0002_auto_20210314_0540'),
    ]

    operations = [
        migrations.AddField(
            model_name='detail',
            name='email',
            field=models.CharField(default='Not available', max_length=50),
        ),
        migrations.AddField(
            model_name='detail',
            name='github',
            field=models.CharField(default='Not available', max_length=50),
        ),
        migrations.AddField(
            model_name='detail',
            name='languages',
            field=models.CharField(default='Not available', max_length=50),
        ),
        migrations.AlterField(
            model_name='detail',
            name='field',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='detail',
            name='name',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
