# Generated by Django 3.1.7 on 2021-03-14 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phonebook', '0003_auto_20210314_0732'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignIn',
            fields=[
                ('username', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
    ]
