# Generated by Django 3.1.7 on 2021-03-14 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phonebook', '0004_signin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='field',
            field=models.CharField(default='Not avaiable', max_length=50),
        ),
    ]
